version: "3.5"
services:
  lumen-task-scheduling:
    image: domenicogaeni/php:8.0-dev
    container_name: lumen-task-scheduling
    user: "www-data:www-data"
    volumes:
      - .:/var/www/html:cached
    ports:
      - ${PHP_HOST_PORT}:80
    command: bash -c "composer install &&
      apache2-foreground"
    networks:
      backend:
        aliases:
          - lumen-task-scheduling

networks:
  backend:
    name: network
